name: Generate Documentation for Github Pages and publish zip of the repo with a pdf documentation to releases

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz texlive-latex-base texlive-fonts-recommended texlive-latex-extra texlive-lang-german latexmk pandoc
          pip install markdown pygments

      - name: Generate Doxygen Documentation (HTML & LaTeX)
        run: |
          cd docs
          doxygen Doxyfile

      - name: Move C HTML to correct folder
        run: |
          mv docs/src/html/c/html/* docs/src/html/c/
          rm -r docs/src/html/c/html

      - name: Compile C Documentation PDF
        run: |
          cd docs/src/html/c/latex
          make
          mv refman.pdf ../../../../../latex/wgr-v-c-docs.pdf

      - name: Download DoxNet Verilog Doc Tool
        run: |
          curl -L https://raw.githubusercontent.com/BTFLV/DoxNet/main/DoxNet.py -o DoxNet.py

      - name: Create Output Folders
        run: |
          mkdir -p docs/src/html/verilog
          mkdir -p docs/latex

      - name: Generate Verilog Documentation
        run: |
          python DoxNet.py --output docs/src/html/verilog --config docs/DoxNet.json

      - name: Upload HTML Documentation as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: doxygen-html
          path: docs/src/html

      - name: Upload PDF Documentation as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: doxygen-pdf
          path: |
            docs/latex/wgr-v-c-docs.pdf
            docs/src/html/wgr-v-verilog-docs.pdf

      - name: Copy index and asic image to GitHub Pages root
        run: |
          cp docs/wgr-v-documentation-index.html docs/src/html/index.html
          cp asic/WGR-V-ASIC_gds_render.jpg docs/src/html/WGR-V-ASIC_gds_render.jpg

      - name: Deploy HTML to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/src/html
          publish_branch: gh-pages

      - name: Create ZIP of the repository
        if: github.ref == 'refs/heads/main'
        run: |
          git archive --format=zip HEAD -o wgr-v.zip

      - name: Install GitHub CLI
        if: github.ref == 'refs/heads/main'
        run: sudo apt-get install -y gh

      - name: Create GitHub Release with Custom Files Only
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete latest --yes || true
          gh release create latest \
            --title "Repo .zip + PDF Dokumentation" \
            --notes "Aktuelles Repo als .zip plus C- und Verilog-Doku als .pdf Dateien." \
            docs/latex/wgr-v-c-docs.pdf \
            docs/src/html/wgr-v-verilog-docs.pdf \
            wgr-v.zip
